### ISSUE TITLE
Proposing some better translation

### ISSUE THREAD

**Issue by ianychoi** [MicrosoftDocs/Contribute.ko-KR#3]
Hello,

I have created a pull request for better translation: https://github.com/MicrosoftDocs/Contribute.ko-KR/pull/2 . Please review this.

With many thanks,

/Ian

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs 기여자 가이드 개요 - Contributor Guide](https://docs.microsoft.com/ko-kr/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute.ko-KR/blob/live/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @ianychoi

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review https://github.com/MicrosoftDocs/Contribute.ko-KR/pull/2 . For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
